crescent-network/crescent

- README.md
- docs/demo/budget_with_farming.md
- x/liquidity/keeper/batch.go
- x/liquidity/keeper/batch_test.go
- x/liquidity/keeper/swap.go
- x/liquidity/keeper/swap_test.go
cherry-pick pull request [#258 from cosmosquad-labs/fix-offer-coin-refund](https://github.com/cosmosquad-labs/squad/pull/258)
- https://github.com/cosmosquad-labs/squad/pull/258
---
> cherry-pick pull request #258 from cosmosquad-labs/fix-offer-coin-refund

- .github/workflows/test.yml
- README.md
- https://github.com/cosmosquad-labs/squad/pull/259
---
> chore: enable codecov #259

- x/farming/keeper/reward.go
- x/farming/keeper/reward_test.go
- https://github.com/cosmosquad-labs/squad/pull/261
---
> fix: skip zero total stakings when allocating rewards #261

- app/app.go
- app/sim_test.go
- x/liquidity/amm/match.go
- x/liquidity/keeper/swap.go
- x/liquidity/keeper/swap_test.go
- x/liquidity/types/order.go
- https://github.com/cosmosquad-labs/squad/pull/265
---
> fix: use truncated open amount before matching #265

- x/liquidstaking/keeper/tally.go
- x/liquidstaking/simulation/proposals.go
- x/liquidstaking/types/expected_keepers.go
- https://github.com/cosmosquad-labs/squad/pull/266
---
> fix: liquidstaking tally map iteration to deterministic #266

- go.mod
- go.sum
- x/farming/keeper/reward.go
- https://github.com/cosmosquad-labs/squad/pull/262
---
> fix: sort map keys before iteration for deterministic execution #262

- README.md
- config-test.yml
- docs/api/claim.md
- docs/api/farming.md
- docs/api/liquidity.md
- docs/api/liquidstaking.md
- docs/cli/claim.md
- docs/cli/farming.md
- docs/cli/liquidity.md
- docs/cli/liquidstaking.md
- x/liquidstaking/client/cli/query.go
- x/liquidstaking/keeper/liquidstaking.go
- https://github.com/cosmosquad-labs/squad/pull/263
---
> docs: add more documents #263

- app/app.go
- app/upgrades/testnet/rc3/upgrade.go
In order to prepare for upgrades, the structure for the upgrade was added to `app/app.go`, `app/upgrades` In addition, `testnet-rc3` upgrade information was added.
---
> feat: add upgrade structure for testnet rc3

- Makefile
(cherry picked from commit d013ef01930ca0f2c9e227c5dc4df34be5842b7e)
- https://github.com/cosmosquad-labs/squad/pull/276
---
> build: set ledger_enabled true as default on makefile

- x/claim/keeper/keeper_test.go
- x/liquidstaking/keeper/grpc_query.go
- x/liquidstaking/keeper/invariants.go
- x/liquidstaking/keeper/keeper_test.go
- x/liquidstaking/keeper/liquidstaking.go
- x/liquidstaking/keeper/liquidstaking_test.go
- x/liquidstaking/keeper/msg_server.go
- x/liquidstaking/keeper/rebalancing.go
- x/liquidstaking/keeper/rebalancing_test.go
- x/liquidstaking/keeper/tally_test.go
- x/liquidstaking/keeper/test_common.go
- x/liquidstaking/simulation/operations.go
- x/liquidstaking/simulation/proposals.go
- x/liquidstaking/types/expected_keepers.go
- x/liquidstaking/types/liquidstaking.go
- x/liquidstaking/types/params.go
- x/liquidstaking/types/params_test.go
- x/liquidstaking/types/rebalancing.go
- x/liquidstaking/types/rebalancing_test.go
- https://github.com/cosmosquad-labs/squad/pull/278
---
> test: add logic and test for liquid unstaking edge cases #278

- x/liquidstaking/keeper/keeper_test.go
- x/liquidstaking/keeper/rebalancing.go
- x/liquidstaking/keeper/rebalancing_test.go
- x/liquidstaking/types/rebalancing.go
- https://github.com/cosmosquad-labs/squad/pull/287
---
> fix: rebalancing logic to avoid redelegation restrictions #287

- types/utils.go
- types/utils_test.go
- x/liquidity/amm/amm.go
- x/liquidity/amm/match.go
- x/liquidity/amm/pool.go
- x/liquidity/amm/pool_test.go
- x/liquidity/keeper/pool.go
- x/liquidity/keeper/pool_test.go
- x/liquidity/keeper/swap_test.go
- x/liquidity/simulation/operations.go
- x/liquidity/spec/08_params.md
- x/liquidity/types/errors.go
- x/liquidity/types/msgs.go
- x/liquidity/types/msgs_test.go
- x/liquidity/types/order.go
- x/liquidity/types/params.go
- x/liquidity/types/util.go
- https://github.com/cosmosquad-labs/squad/pull/285
---
> fix: mitigate integer overflow issues in x/liquidity #285

- app/params/weights.go
- types/utils.go
- x/claim/simulation/genesis.go
- x/claim/simulation/genesis_test.go
- x/claim/simulation/operations.go
- x/farming/client/testutil/cli_helpers.go
- x/farming/simulation/genesis.go
- x/farming/simulation/genesis_test.go
- x/farming/simulation/operations.go
- x/farming/simulation/operations_test.go
- x/farming/simulation/params_test.go
- x/farming/simulation/proposals.go
- x/farming/simulation/proposals_test.go
- x/liquidity/simulation/operations.go
- x/liquidstaking/simulation/operations.go
- x/liquidstaking/simulation/proposals.go
- https://github.com/cosmosquad-labs/squad/pull/288
---
> fix: fix farming simulation test #288

- app/app.go
- app/upgrades/testnet/rc4/upgrade.go
> feat: add testnet v1.0.0-rc4 upgrade

- x/mint/abci.go
- x/mint/keeper/keeper.go
- https://github.com/cosmosquad-labs/squad/pull/290
---
> fix: fix typo on mint module #290

- CHANGELOG.md
- README.md
> docs: add changelog and update readme version

- .github/labeler.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/dependency.yml
- .github/workflows/janitor.yml
- .github/workflows/labeler.yml
- .github/workflows/linkchecker.yml
- .github/workflows/lint-pr.yml
- .github/workflows/stale.yml
This PR is cherry picked from [this PR](https://github.com/cosmosquad-labs/squad/pull/301).
---
> env: add more workflow actions #301

- x/claim/client/cli/query.go
- x/farming/client/cli/query.go
- x/liquidity/client/cli/query.go
- x/liquidstaking/client/cli/query.go
This PR is cherry picked from [this PR](https://github.com/cosmosquad-labs/squad/pull/298).
---
> fix: fix to use query context #298

- .github/labeler.yml
- x/claim/module.go
- x/claim/simulation/operations.go
- x/claim/simulation/operations_test.go
- x/claim/types/expected_keepers.go
- https://github.com/cosmosquad-labs/squad/pull/292
- https://github.com/cosmosquad-labs/squad/pull/304
---
> fix: fix simulation for the claim module #292 #304

- docs/cli/claim.md
- docs/cli/farming.md
- docs/cli/liquidity.md
- docs/cli/liquidstaking.md
This PR is cherry picked from https://github.com/cosmosquad-labs/squad/pull/308
---
> docs: use Ignite CLI

- x/liquidity/amm/match.go
- x/liquidity/keeper/bench_test.go
- x/liquidity/keeper/swap_test.go
- https://github.com/cosmosquad-labs/squad/pull/326
---
> fix: fix bug in matching logic #326

- docs/whitepapers/liquidity/pool.md
- x/liquidity/spec/01_concepts.md
- x/liquidity/spec/02_state.md
- x/liquidity/spec/04_messages.md
- x/liquidity/spec/07_events.md
- https://github.com/cosmosquad-labs/squad/pull/325
---
> docs: add liquidity whitepaper (pool) #325

- Makefile
- go.mod
- go.sum
- e.g. `make install COSMOS_BUILD_OPTIONS=rocksdb TENDERMINT_BUILD_OPTIONS=rocksdb BUILD_TAGS=rocksdb`
- https://github.com/cosmosquad-labs/squad/pull/327
---
> build: add dbbackend selecting tag on makefile

- docs/whitepapers/liquidity/matching.md
- x/liquidity/spec/01_concepts.md
- x/liquidity/spec/03_state_transitions.md
- https://github.com/cosmosquad-labs/squad/pull/328
- https://github.com/cosmosquad-labs/squad/pull/337
---
> docs: add liquidity module white paper (matching) #328 #337

- CHANGELOG.md
- app/app.go
- app/upgrades/mainnet/v3/upgrade.go
- app/upgrades/mainnet/v3/upgrade_test.go
- x/liquidity/keeper/params.go
- x/liquidity/module.go
> build: add v3 upgrade handler

- docs/cli/liquidity.md
- x/farming/spec/01_concepts.md
- x/farming/spec/04_messages.md
- x/liquidity/client/cli/tx.go
- https://github.com/cosmosquad-labs/squad/pull/355
---
> feat: add MM order cli commands and update api docs #355

- config-test.yml
- docs/api/marketmaker.md
- docs/cli/marketmaker.md
- x/marketmaker/client/cli/tx.go
- x/marketmaker/client/cli/utils_test.go
This PR adds docs for the `marketmaker` module
---
> docs: add docs for the marketmaker module

- docs/whitepapers/marketmaker/scoring.md
- https://github.com/cosmosquad-labs/squad/pull/357
---
> docs: ameding equation on market maker scoring #357

- docs/whitepapers/marketmaker/scoring.md
Fix the example number as a result of considering the decimal point
- https://github.com/cosmosquad-labs/squad/pull/358
---
> docs: fix mm paper example number #358

- app/upgrades/mainnet/v3/upgrade.go
- app/upgrades/mainnet/v3/upgrade_test.go
- fix `marketmakerparams.DepositAmount` to 1000000000ucre from 1000000000stake
- fix relevant test case
- https://github.com/crescent-network/crescent/pull/59
---
> fix: upgrade handler for v3 upgrade

- x/farming/handler.go
- x/farming/handler_test.go
- x/farming/keeper/epoch.go
- x/farming/keeper/keeper_test.go
- x/farming/keeper/plan.go
- x/farming/keeper/plan_test.go
- x/farming/keeper/proposal_handler_test.go
- x/farming/module.go
- x/farming/module_test.go
- x/farming/types/errors.go
- x/liquidity/simulation/genesis.go
- x/liquidity/simulation/params_test.go
- https://github.com/cosmosquad-labs/squad/pull/381
- https://github.com/cosmosquad-labs/squad/pull/382
---
> feat: disable x/farming handlers and prepare for the deprecation #381 #382

- x/farm/keeper/plan.go
- x/farm/keeper/plan_test.go
- x/farm/keeper/util.go
- https://github.com/cosmosquad-labs/squad/pull/383
---
> fix: check if farmer exists when allocating rewards to target denom #383

- docs/api/claim.md
- docs/api/farm.md
- docs/api/farming.md
- docs/api/liquidfarming.md
- docs/api/liquidity.md
- docs/api/marketmaker.md
- docs/cli/claim.md
- docs/cli/farming.md
- docs/cli/liquidfarming.md
- docs/cli/liquidity.md
- docs/cli/liquidstaking.md
- x/liquidfarming/spec/07_params.md
- https://github.com/cosmosquad-labs/squad/pull/368
---
> docs: organize docs #368

- docs/cli/liquidfarming.md
- x/liquidfarming/client/cli/flags.go
- x/liquidfarming/client/cli/query.go
> feat: add pagination and auction status optional flags for CLI queries

- .github/CODEOWNERS
This PR adds new primary code owners @richard-bachman and @lv-koala.
closes: #113
---
> docs: update CODEOWNERS file

- x/liquidity/spec/01_concepts.md
Fixes a typo.
closes: #91 
- 
---
> fix: fix a typographical error

- x/liquidity/client/cli/query.go
- x/lpfarm/client/cli/query.go
- x/marketmaker/client/cli/query.go
> feat: add missing pagination flags for CLI commands

- x/liquidfarming/keeper/auction.go
- x/liquidfarming/keeper/auction_test.go
> fix: validate auction status when placing a bid

- x/liquidfarming/client/testutil/suite.go
- x/liquidfarming/keeper/auction.go
- x/liquidfarming/keeper/auction_test.go
- x/liquidfarming/keeper/keeper_test.go
- x/liquidfarming/keeper/liquidfarm.go
- x/liquidfarming/keeper/liquidfarm_test.go
- x/liquidfarming/types/errors.go
> fix: fix refund previous bid

- app/upgrades/mainnet/v4/upgrade.go
This PR simply disables `HostEnabled`. 
---
> feat: disable host enabled

- .github/workflows/test.yml
- CHANGELOG.md
> docs: release v4

- app/app.go
- app/upgrades/mainnet/v5/upgrade.go
- cmd/crescentd/cmd/root.go
During this v5 upgrade and migration, a large number of events could be emited, and the possibility of stability issues in some nodes was confirmed, so a flag that can be used at this time was added
> feat: Add flag to disable events that occur during v5 upgrade, migration

- app/upgrades/mainnet/v5/upgrade.go
Set default params for mainnet v5 upgrade.
> fix: update default params for mainnet upgrade

- x/exchange/keeper/order.go
- x/exchange/keeper/order_test.go
We can check base coin balance before executing sell market orders, unlike buy orders.
This PR adds the check to `PlaceMarketOrder`.
> fix: check base coin balance in PlaceMarketOrder

- x/amm/client/cli/tx.go
- x/exchange/client/cli/tx.go
Update help msgs for x/amm, x/exchange gov proposal commands.
> fix: fix proposal tx help msgs

- app/upgrades/mainnet/v5/param_changes.go
- app/upgrades/mainnet/v5/upgrade.go
- app/upgrades/mainnet/v5/upgrade_test.go
- x/liquidamm/keeper/auction_test.go
- x/liquidamm/types/params.go
- x/liquidity/keeper/store.go
Set default market/pool params in upgrade handler. The values are picked by a specific rule.
> feat: set default market/pool params in upgrade handler

- x/exchange/keeper/batch_test.go
- x/exchange/types/matching.go
This PR fixes a bug in batch matching. Last price was being set to 0(nil?) when there was a matching at phase 1 but no matching at phase 2.
> fix: fix bug in batch matching
