crescent-network/crescent

- CHANGELOG.md
- README.md
- app/upgrades/mainnet/v1.1.0/upgrade.go
- x/claim/keeper/claim.go
- x/claim/keeper/claim_test.go
- x/claim/types/expected_keepers.go
This PR fixes gas consumption issue for `ConditionTypeVote` for the `claim` module.
---
> fix: fix gas consumption issue for `ConditionTypeVote`

- x/liquidity/keeper/swap.go
- x/liquidity/keeper/swap_test.go
- https://github.com/cosmosquad-labs/squad/pull/296
- https://github.com/cosmosquad-labs/squad/pull/299
---
> fix: optimize CancelAllOrders gas usage, fix offer coin checking #296 #299

- .github/workflows/test.yml
Fixed an issue where `*.pb.go` exclusions were missing from the codecov test
- https://github.com/cosmosquad-labs/squad/pull/324
- broken on https://github.com/crescent-network/crescent/pull/38
---
> build: fix codecov excluding pb.go #324

- x/liquidity/amm/match.go
- x/liquidity/amm/orderbook.go
- x/liquidity/amm/pool.go
- x/liquidity/amm/pool_test.go
- x/liquidity/keeper/swap_test.go
- do not add order with zero matchable amount to order book
- check if result of BuyAmountTo/SellAmountUnder is positive
- set matched to true only when order distribution has happened
- fix bug in pool order amount calculation(use swap price instead of adjusted price)
- https://github.com/cosmosquad-labs/squad/pull/323
---
> fix: bug in order book and pool orders calculation #323

- x/liquidity/keeper/grpc_query.go
- x/liquidity/keeper/swap_test.go
- x/liquidity/types/example_orderbook_test.go
- x/liquidity/types/orderbook.go
- x/liquidity/types/orderbook_test.go
- https://github.com/cosmosquad-labs/squad/pull/333
---
> fix: return as many ticks as `numTicks` in `MakeOrderBookResponse` #333

- CHANGELOG.md
- x/liquidity/keeper/pool.go
- x/liquidity/keeper/pool_test.go
- x/liquidity/types/errors.go
- x/liquidity/types/params.go
Add `MaxNumActivePoolsPerPair` global constant.
- https://github.com/cosmosquad-labs/squad/pull/340
---
> fix: limit the number of active pools in a pair #340

- CHANGELOG.md
- x/liquidity/keeper/grpc_query.go
- x/liquidity/types/example_orderbook_test.go
- x/liquidity/types/orderbook.go
- x/liquidity/types/orderbook_test.go
- https://github.com/cosmosquad-labs/squad/pull/341
---
> refactor!: detailed configuration for order book responses #341

- CHANGELOG.md
- x/liquidstaking/keeper/keeper_test.go
- x/liquidstaking/keeper/tally.go
- x/liquidstaking/keeper/tally_test.go
- x/liquidstaking/types/expected_keepers.go
Fixed a bug that missed the calculation of the voting power of the pool coin that was not in the user's balance when calculating the liquid stacking voting power at the /liquidstaking/v1beta1/voting_power/{voter} grpc endpoint
Fixed to create a bTokenSharePerPoolCoinMap for all pool coins before calculating the voting power for user's farming positions
- https://github.com/cosmosquad-labs/squad/pull/342
---
> fix: bug some pool coins voting power omitted on voting_powers #342

- CHANGELOG.md
- x/liquidstaking/keeper/keeper_test.go
- x/liquidstaking/keeper/tally.go
- x/liquidstaking/keeper/tally_test.go
Fixed a bug that missed the calculation of the voting power of the pool coin that was not in the user's balance when calculating the liquid stacking voting power at `SetLiquidStakingVotingPowers`
Fixed to create a `bTokenSharePerPoolCoinMap` for all pool coins before calculating the voting power for user's farming positions
- https://github.com/cosmosquad-labs/squad/pull/346
---
> fix: calculation bug of liquidstaking voting_power #346

- x/liquidity/client/cli/query.go
- x/liquidity/types/msgs.go
- x/liquidity/types/msgs_test.go
This PR fixes two bugs in the liquidity module.
- https://github.com/cosmosquad-labs/squad/pull/365
- https://github.com/cosmosquad-labs/squad/issues/363
---
> fix: reject same base/quote coin denom in `MsgCreatePair` #365

- x/liquidstaking/keeper/grpc_query_test.go
- x/liquidstaking/simulation/operations_test.go
- x/liquidstaking/simulation/proposals_test.go
- x/liquidstaking/types/liquidstaking_test.go
- x/liquidstaking/types/msgs_test.go
- https://github.com/cosmosquad-labs/squad/pull/386
---
> test: increase test coverage of liquidstaking #386

- x/liquidfarming/types/codec.go
This PR is minor patch to register legacy amino codec for Ledger hardware users.
---
> fix: register legacy amino codec for ledger use

- x/liquidfarming/keeper/auction.go
- x/liquidfarming/keeper/auction_test.go
> fix: fix incorrect rewards value for RewardsAuction

- x/lpfarm/keeper/plan.go
- x/lpfarm/keeper/plan_test.go
This PR fixes a bug when recording previous share, which was not setting previous share to nil when pools are excluded from the rewards allocation.
- 
---
> fix: set previous share to nil for excluded pools

- docs/api/farming.md
- docs/cli/liquidity.md
This PR adjusts format for `api` and `cli` documents and provide more examples 
---
> docs: format docs and provide more examples for cli document

- go.mod
- go.sum
The build issue below occurs on macOS 12.0 or higher when installing libraries with "make install" command. It's occurred because the "kIOMasterPortDefault" is deprecated in macOS 12.0.
- warning: 'kIOMasterPortDefault' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
The issue is related to "zondax/hid v0.9.0" among the installed libraries. On the [zondax/hid releases page](https://github.com/Zondax/hid/releases), the version v0.9.1 is released for macOS 12.0 or higher. So, I changed the version of zondax/hid in the "go.mod" file to v0.9.1.
Here are links to similar issues in other repositories.
- [https://github.com/kovidgoyal/kitty/issues/3719](https://github.com/kovidgoyal/kitty/issues/3719)
- [https://github.com/datreeio/datree/issues/512](https://github.com/d …
> chore: change a zondax/hid version for mac os

- CHANGELOG.md
- README.md
- go.mod
- go.sum
bump cosmos-sdk to [v1.2.0-sdk-0.45.10](https://github.com/crescent-network/cosmos-sdk/releases/tag/v1.2.0-sdk-0.45.10) to use `MinInitialDepositRatio` as 0.5 for proposal submission, details on https://github.com/crescent-network/cosmos-sdk/pull/2
- https://github.com/crescent-network/cosmos-sdk/releases/tag/v1.2.0-sdk-0.45.10
- https://github.com/crescent-network/cosmos-sdk/pull/2
---
> feat!: bump cosmos-sdk to v1.2.0-sdk-0.45.10 to use MinInitialDepositRatio

- x/liquidity/keeper/invariants.go
- x/liquidity/keeper/invariants_test.go
- x/liquidity/module.go
This PR adds an `x/liquidity` invariant check for the recently added `NumMMOrders` state.
- 
---
> feat: add `NumMMOrdersInvariant` invariant check

- docs/whitepapers/marketmaker/scoring.md
> docs: Update scoring.md

- app/ante/msg_ante.go
- app/ante/msg_ante_test.go
- app/params/weights.go
- x/liquidity/simulation/operations_test.go
Continued PR from https://github.com/crescent-network/crescent/pull/159
- 
---
> feat!: add ante msg filter for mixed batch msg, deprecated module msgs

- app/testutil/test_suite.go
- x/exchange/keeper/invariants.go
- x/exchange/keeper/order.go
- x/exchange/keeper/order_test.go
https://github.com/crescent-network/crescent/blob/92ee8b8cf0eced61969f214dd3d72497a0b72091/x/exchange/keeper/order.go#L150-L162
The bug was because we're trying to use `res.ExecutedQuantity` when `isBatch` is true. `res` was not set when `isBatch`.
> fix: fix bug in placeLimitOrder and exchange invariant checks

- x/amm/keeper/position_test.go
- x/amm/keeper/tick.go
allow negative farmingRewardsGrowthInside, like feeGrowthInside.
> fix: fix bug in farmingRewardsGrowthInside

- Makefile
- app/ante/msg_ante.go
- app/app.go
- app/params/weights.go
- app/sim_test.go
- x/liquidstaking/module.go
- x/liquidstaking/simulation/operations.go
- x/liquidstaking/simulation/operations_test.go
> fix: disable deprecated modules and fix simulation

- x/exchange/keeper/order.go
- x/exchange/keeper/order_test.go
This PR fixes a bug in `NumMMOrders` calculation. The bug occurs when an orderer places an MM order while matching against own MM orders.
> fix: fix bug in NumMMOrders calculation

- app/upgrades/mainnet/v5/upgrade.go
- During revert liquidfarming + add liquidamm module, there was an issue where liquidamm store key was missing in v5 `StoreUpgrades`
- https://github.com/crescent-network/crescent/pull/171
---
> fix: add liquidamm module to v5 store upgrades

- x/exchange/keeper/batch.go
- x/exchange/types/matching.go
If there was no matching in batch phase, do not update `LastMatchingHeight`. Previously, it has been updated in every block.
> fix: do not update matching height when there's no matching

- app/upgrades/mainnet/v5/upgrade.go
- x/amm/keeper/order_test.go
- x/amm/keeper/pool.go
- x/amm/keeper/pool_bench_test.go
- x/amm/keeper/pool_test.go
- x/amm/simulation/operations.go
- x/amm/types/math_test.go
- x/amm/types/params.go
- x/amm/types/tick.go
- x/amm/types/tick_test.go
- x/exchange/keeper/batch.go
- x/exchange/keeper/order.go
Improve pool order performance by finding the next order price derived by current pool state.
Also, pass `quoteLimit` properly for buy orders.
> refactor: improve pool order performance

- x/exchange/abci.go
To prevent a chain halt caused by an uncaught error from `RunBatchMatching`, use cached context and recover panics from it.
> refactor: safely run batch matching using cached ctx

- x/liquidamm/keeper/auction_test.go
- x/liquidamm/keeper/grpc_query.go
- x/liquidamm/keeper/grpc_query_test.go
- x/liquidamm/keeper/public_position_test.go
- x/liquidamm/types/auction_test.go
- x/liquidamm/types/msgs_test.go
- x/liquidamm/types/public_position.go
- x/liquidamm/types/public_position_test.go
Rename `lashare*` to `sb*`(snowball).
> refactor: rename lashare to sb(snowball)

- x/amm/keeper/pool.go
- x/amm/keeper/pool_test.go
There was a bug which causes `IteratePoolOrders` to run forever. Fix it by correctly checking if the next order price is not same as current price.
> fix: prevent IteratePoolOrders to run forever

- x/amm/keeper/grpc_query_test.go
- x/amm/keeper/pool.go
- x/amm/types/tick_test.go
- x/exchange/keeper/grpc_query.go
Handle edge case when `orderPrice == currentPrice`. And also handle non-positive order book price when querying order books.
> fix: fix bug in order book query and IteratePoolOrders

- app/upgrades/mainnet/v5/upgrade.go
- app/upgrades/mainnet/v5/upgrade_test.go
Currently `LastMarketId` is not being updated in the upgrade handler, so if someone creates a new market after upgrade, then the existing markets would be overwritten since the new market's id would start from 1 again. This PR fixes the bug by correctly setting last market id.
> fix: set last market id in upgrade handler

- x/exchange/abci.go
Events emitted inside cached context were being ignored, so this PR fixes that bug.
> fix: pass events emitted inside cached context to original context

- x/amm/keeper/farming_test.go
- x/amm/keeper/invariants_test.go
- x/amm/keeper/order_test.go
- x/amm/keeper/position_test.go
- x/amm/keeper/sim_test.go
- x/exchange/keeper/order.go
- x/exchange/keeper/order_test.go
- x/exchange/simulation/operations.go
- x/exchange/simulation/operations_test.go
This PR applies `MaxOrderPriceRatio` limit to market orders.
> fix: limit market orders' price impact to MaxOrderPriceRatio

- app/app.go
- types/utils.go
- x/liquidstaking/keeper/keeper.go
- x/liquidstaking/keeper/keeper_test.go
- x/liquidstaking/keeper/tally.go
- x/liquidstaking/keeper/tally_test.go
- x/liquidstaking/spec/01_concepts.md
- x/liquidstaking/spec/06_hooks.md
- x/liquidstaking/types/expected_keepers.go
This PR updates x/liquidstaking to use new modules(x/amm, x/liquidamm) instead of deprecated x/liquidity.
> fix: update x/liquidstaking to use new modules

- x/exchange/keeper/invariants.go
- x/exchange/keeper/matching.go
- x/exchange/keeper/order_test.go
- x/exchange/types/mem_order.go
Force `Paid`/`Received`/`RemainingDeposit` to all be integers for user orders. This would conservatively prevent some unknown edge cases.
> fix: force paid/received/deposit to be integers for user orders

- app/testutil/amm.go
- x/amm/keeper/grpc_query_test.go
- x/amm/keeper/pool_test.go
- x/amm/keeper/source.go
- x/amm/types/expected_keepers.go
- x/exchange/types/market.go
> fix: limit pool order price range by MaxOrderPriceRatio

- x/amm/keeper/grpc_query_test.go
- x/amm/keeper/pool_bench_test.go
- x/exchange/keeper/grpc_query.go
This PR makes `OrderBook` query to use `MaxOrderPriceRatio` when constructing the order book view. The logic is same as Crescent v4.
> fix: fix order book query to use MaxOrderPriceRatio

- x/amm/keeper/position.go
- x/amm/keeper/position_test.go
- x/liquidstaking/keeper/keeper_test.go
- x/liquidstaking/keeper/tally_test.go
This PR fixes a bug in `PositionAssets`, which causes panic in tally logic when the voter has zero liquidity positions. Note: If someone removes all liquidity in a position, the position is not deleted and remaining as zero liquidity positions.
> fix: fix bug in PositionAssets when position liquidity is zero

- x/amm/keeper/farming.go
- x/amm/keeper/pool.go
- x/amm/keeper/position.go
- x/amm/keeper/position_test.go
- x/amm/keeper/source.go
- x/liquidamm/keeper/genesis.go
This PR fixes missing `Set~Index` calls in x/liquidamm's `InitGenesis`. Also, check if amount is all positive when calling `BankKeeper.SendCoins`.
> fix: set public position indexes in InitGenesis and fix minor issues
